name: Regenerate

on:
  push:
    branches:
      - main
  schedule:
    # Schedule to run at 00:00 and 12:00 every day
    - cron: '0 0,12 * * *'

jobs:
  run-bun-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Fetch Stats
        run: bun run stats
        env:
          API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
